File paths are: ['./code-dataset/demo-staging-area/adjacency-Patched.py', './code-dataset/demo-staging-area/adafactor_optimizer-Patched.py', './code-dataset/demo-staging-area/ant-Patched.py', './code-dataset/demo-staging-area/affine-Patched.py', './code-dataset/demo-staging-area/addition-Patched.py', './code-dataset/demo-staging-area/agent-Patched.py', './code-dataset/demo-staging-area/aggregation-Patched.py', './code-dataset/demo-staging-area/aggregation_extraction-Patched.py', './code-dataset/demo-staging-area/affine_linear_operator_test-Patched.py', './code-dataset/demo-staging-area/anchor_generator-Patched.py', './code-dataset/demo-staging-area/anchor-Patched.py', './code-dataset/demo-staging-area/all_tests-Patched.py', './code-dataset/demo-staging-area/all_models-Patched.py', './code-dataset/demo-staging-area/adaptive_softmax-Patched.py', './code-dataset/demo-staging-area/advanced_mia_example-Patched.py', './code-dataset/demo-staging-area/adult_tutorial-Patched.py', './code-dataset/demo-staging-area/add_context_to_examples_tf2_test-Patched.py', './code-dataset/demo-staging-area/affine_test-Patched.py', './code-dataset/demo-staging-area/anchor_generator_test-Patched.py', './code-dataset/demo-staging-area/anchor_generator_builder-Patched.py', './code-dataset/demo-staging-area/alexnet-Patched.py', './code-dataset/demo-staging-area/anchor_test-Patched.py', './code-dataset/demo-staging-area/add_context_to_examples-Patched.py', './code-dataset/demo-staging-area/affine_linear_operator-Patched.py', './code-dataset/demo-staging-area/alexnet_test-Patched.py', './code-dataset/demo-staging-area/advanced_mia_test-Patched.py', './code-dataset/demo-staging-area/active_vision_dataset_env-Patched.py', './code-dataset/demo-staging-area/add-Patched.py', './code-dataset/demo-staging-area/advanced_mia-Patched.py', './code-dataset/demo-staging-area/albert_encoder_test-Patched.py', './code-dataset/demo-staging-area/ant_maze_env-Patched.py', './code-dataset/demo-staging-area/adversarial_losses-Patched.py', './code-dataset/demo-staging-area/albert_encoder-Patched.py', './code-dataset/demo-staging-area/anchor_generator_builder_test-Patched.py', './code-dataset/demo-staging-area/and-Patched.py', './code-dataset/demo-staging-area/affine_scalar_test-Patched.py', './code-dataset/demo-staging-area/adjacency_test-Patched.py', './code-dataset/demo-staging-area/analysis-Patched.py', './code-dataset/demo-staging-area/affine_scalar-Patched.py', './code-dataset/demo-staging-area/adaptive_softmax_test-Patched.py']
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/aggregation_extraction-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/aggregation_extraction-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/aggregation_extraction-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f3096006fd0 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/aggregation-Patched.py", line 10
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/aggregation-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/aggregation-Patched.py", line 10\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f3096006a00 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/affine_linear_operator_test-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/affine_linear_operator_test-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/affine_linear_operator_test-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f309600d460 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/affine-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/affine-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/affine-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f30970c4b50 state=finished returned CompletedProcess>
Standard Error 
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/adafactor_optimizer-Patched.py'], returncode=0, stdout=b'', stderr=b'')
<Future at 0x7f30970c41f0 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/anchor-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/anchor-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/anchor-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f309600df40 state=finished returned CompletedProcess>
Standard Error Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/all_models-Patched.py", line 11, in <module>
    from official.projects.unified_detector.modeling import universal_detector
ModuleNotFoundError: No module named 'official'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/all_models-Patched.py'], returncode=1, stdout=b'', stderr=b'Traceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/all_models-Patched.py", line 11, in <module>\n    from official.projects.unified_detector.modeling import universal_detector\nModuleNotFoundError: No module named \'official\'\n')
<Future at 0x7f3096017340 state=finished returned CompletedProcess>
Standard Error Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/adaptive_softmax-Patched.py", line 13, in <module>
    import gin
ModuleNotFoundError: No module named 'gin'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/adaptive_softmax-Patched.py'], returncode=1, stdout=b'', stderr=b'Traceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/adaptive_softmax-Patched.py", line 13, in <module>\n    import gin\nModuleNotFoundError: No module named \'gin\'\n')
<Future at 0x7f3096017460 state=finished returned CompletedProcess>
Standard Error Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/ant-Patched.py", line 13, in <module>
    import mujoco_py
ModuleNotFoundError: No module named 'mujoco_py'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/ant-Patched.py'], returncode=1, stdout=b'', stderr=b'Traceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/ant-Patched.py", line 13, in <module>\n    import mujoco_py\nModuleNotFoundError: No module named \'mujoco_py\'\n')
<Future at 0x7f30970c4640 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/adult_tutorial-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/adult_tutorial-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/adult_tutorial-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f30960176a0 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/add_context_to_examples_tf2_test-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/add_context_to_examples_tf2_test-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/add_context_to_examples_tf2_test-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f30960177c0 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/affine_test-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/affine_test-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/affine_test-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f30960178e0 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/anchor_generator_builder-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/anchor_generator_builder-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/anchor_generator_builder-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f3096017b20 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/alexnet-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/alexnet-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/alexnet-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f3096017c40 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/add_context_to_examples-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/add_context_to_examples-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/add_context_to_examples-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f3096017e80 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/affine_linear_operator-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/affine_linear_operator-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/affine_linear_operator-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f3096017fa0 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/alexnet_test-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/alexnet_test-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/alexnet_test-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f309601e100 state=finished returned CompletedProcess>
Standard Error 
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/active_vision_dataset_env-Patched.py'], returncode=0, stdout=b'', stderr=b'')
<Future at 0x7f309601e340 state=finished returned CompletedProcess>
Standard Error Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/advanced_mia_test-Patched.py", line 14, in <module>
    from tensorflow_privacy.privacy.privacy_tests.membership_inference_attack import advanced_mia as amia
ModuleNotFoundError: No module named 'tensorflow_privacy'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/advanced_mia_test-Patched.py'], returncode=1, stdout=b'', stderr=b'Traceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/advanced_mia_test-Patched.py", line 14, in <module>\n    from tensorflow_privacy.privacy.privacy_tests.membership_inference_attack import advanced_mia as amia\nModuleNotFoundError: No module named \'tensorflow_privacy\'\n')
<Future at 0x7f309601e220 state=finished returned CompletedProcess>
Standard Error Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/advanced_mia-Patched.py", line 14, in <module>
    import scipy.stats
ModuleNotFoundError: No module named 'scipy'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/advanced_mia-Patched.py'], returncode=1, stdout=b'', stderr=b'Traceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/advanced_mia-Patched.py", line 14, in <module>\n    import scipy.stats\nModuleNotFoundError: No module named \'scipy\'\n')
<Future at 0x7f309601e580 state=finished returned CompletedProcess>
Standard Error 2023-02-02 21:29:06.055561: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-02 21:29:06.219203: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-02 21:29:06.273150: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-02 21:29:07.037137: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.037176: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.037180: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/anchor_generator-Patched.py'], returncode=0, stdout=b'', stderr=b"2023-02-02 21:29:06.055561: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2023-02-02 21:29:06.219203: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2023-02-02 21:29:06.273150: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n2023-02-02 21:29:07.037137: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.037176: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.037180: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n")
<Future at 0x7f309600da60 state=finished returned CompletedProcess>
Standard Error 2023-02-02 21:29:06.052814: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-02 21:29:06.219203: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-02 21:29:06.273148: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-02 21:29:07.027097: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.027147: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.027153: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/adjacency-Patched.py", line 13, in <module>
    from tensorflow_gnn.graph import graph_constants as const
ModuleNotFoundError: No module named 'tensorflow_gnn'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/adjacency-Patched.py'], returncode=1, stdout=b'', stderr=b'2023-02-02 21:29:06.052814: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2023-02-02 21:29:06.219203: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2023-02-02 21:29:06.273148: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n2023-02-02 21:29:07.027097: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer.so.7\'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.027147: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer_plugin.so.7\'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.027153: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\nTraceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/adjacency-Patched.py", line 13, in <module>\n    from tensorflow_gnn.graph import graph_constants as const\nModuleNotFoundError: No module named \'tensorflow_gnn\'\n')
<Future at 0x7f30970bb1c0 state=finished returned CompletedProcess>
Standard Error 2023-02-02 21:29:06.068012: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-02 21:29:06.232192: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-02 21:29:06.284912: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-02 21:29:07.036235: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.036285: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.036291: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/agent-Patched.py", line 12, in <module>
    import gin.tf
ModuleNotFoundError: No module named 'gin'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/agent-Patched.py'], returncode=1, stdout=b'', stderr=b'2023-02-02 21:29:06.068012: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2023-02-02 21:29:06.232192: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2023-02-02 21:29:06.284912: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n2023-02-02 21:29:07.036235: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer.so.7\'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.036285: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer_plugin.so.7\'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.036291: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\nTraceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/agent-Patched.py", line 12, in <module>\n    import gin.tf\nModuleNotFoundError: No module named \'gin\'\n')
<Future at 0x7f30960065b0 state=finished returned CompletedProcess>
Standard Error Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/ant_maze_env-Patched.py", line 10, in <module>
    from environments.maze_env import MazeEnv
ModuleNotFoundError: No module named 'environments'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/ant_maze_env-Patched.py'], returncode=1, stdout=b'', stderr=b'Traceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/ant_maze_env-Patched.py", line 10, in <module>\n    from environments.maze_env import MazeEnv\nModuleNotFoundError: No module named \'environments\'\n')
<Future at 0x7f309601e7c0 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/adversarial_losses-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/adversarial_losses-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/adversarial_losses-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f309601e8e0 state=finished returned CompletedProcess>
Standard Error 2023-02-02 21:29:06.165186: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-02 21:29:06.415429: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-02 21:29:06.455077: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-02 21:29:07.211448: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.218635: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.218717: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/all_tests-Patched.py", line 12, in <module>
    from tensorflow_compression.python.datasets.y4m_dataset_test import *
ModuleNotFoundError: No module named 'tensorflow_compression'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/all_tests-Patched.py'], returncode=1, stdout=b'', stderr=b'2023-02-02 21:29:06.165186: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2023-02-02 21:29:06.415429: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2023-02-02 21:29:06.455077: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n2023-02-02 21:29:07.211448: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer.so.7\'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.218635: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer_plugin.so.7\'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.218717: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\nTraceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/all_tests-Patched.py", line 12, in <module>\n    from tensorflow_compression.python.datasets.y4m_dataset_test import *\nModuleNotFoundError: No module named \'tensorflow_compression\'\n')
<Future at 0x7f30960171c0 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/anchor_generator_builder_test-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/anchor_generator_builder_test-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/anchor_generator_builder_test-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f309601eb20 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/affine_scalar_test-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/affine_scalar_test-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/affine_scalar_test-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f309601ed60 state=finished returned CompletedProcess>
Standard Error 2023-02-02 21:29:06.476686: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-02 21:29:06.631535: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-02 21:29:06.678991: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-02 21:29:07.323784: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.323835: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.323842: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/anchor_generator_test-Patched.py", line 13, in <module>
    from official.vision.ops import anchor_generator
ModuleNotFoundError: No module named 'official'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/anchor_generator_test-Patched.py'], returncode=1, stdout=b'', stderr=b'2023-02-02 21:29:06.476686: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2023-02-02 21:29:06.631535: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2023-02-02 21:29:06.678991: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n2023-02-02 21:29:07.323784: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer.so.7\'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.323835: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer_plugin.so.7\'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.323842: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\nTraceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/anchor_generator_test-Patched.py", line 13, in <module>\n    from official.vision.ops import anchor_generator\nModuleNotFoundError: No module named \'official\'\n')
<Future at 0x7f3096017a00 state=finished returned CompletedProcess>
Standard Error 2023-02-02 21:29:06.637973: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-02 21:29:06.773675: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-02 21:29:06.809393: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-02 21:29:07.397226: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.397358: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.397378: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/anchor_test-Patched.py", line 14, in <module>
    from official.vision.ops import anchor
ModuleNotFoundError: No module named 'official'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/anchor_test-Patched.py'], returncode=1, stdout=b'', stderr=b'2023-02-02 21:29:06.637973: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2023-02-02 21:29:06.773675: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2023-02-02 21:29:06.809393: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n2023-02-02 21:29:07.397226: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer.so.7\'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.397358: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer_plugin.so.7\'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.397378: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\nTraceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/anchor_test-Patched.py", line 14, in <module>\n    from official.vision.ops import anchor\nModuleNotFoundError: No module named \'official\'\n')
<Future at 0x7f3096017d60 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/affine_scalar-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/affine_scalar-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/affine_scalar-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f3096025100 state=finished returned CompletedProcess>
Standard Error File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/adaptive_softmax_test-Patched.py", line 11
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/adaptive_softmax_test-Patched.py'], returncode=1, stdout=b'', stderr=b'  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/adaptive_softmax_test-Patched.py", line 11\n    from __future__ import absolute_import\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nSyntaxError: from __future__ imports must occur at the beginning of the file\n')
<Future at 0x7f3096025220 state=finished returned CompletedProcess>
Standard Error 2023-02-02 21:29:06.914037: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-02 21:29:07.043437: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-02 21:29:07.094004: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-02 21:29:07.694511: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.694550: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.694555: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/add-Patched.py", line 11, in <module>
    from onnx_tf.handlers.backend_handler import BackendHandler
ModuleNotFoundError: No module named 'onnx_tf'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/add-Patched.py'], returncode=1, stdout=b'', stderr=b'2023-02-02 21:29:06.914037: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2023-02-02 21:29:07.043437: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2023-02-02 21:29:07.094004: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n2023-02-02 21:29:07.694511: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer.so.7\'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.694550: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer_plugin.so.7\'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.694555: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\nTraceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/add-Patched.py", line 11, in <module>\n    from onnx_tf.handlers.backend_handler import BackendHandler\nModuleNotFoundError: No module named \'onnx_tf\'\n')
<Future at 0x7f309601e460 state=finished returned CompletedProcess>
Standard Error 2023-02-02 21:29:06.758613: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-02 21:29:06.919531: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-02 21:29:06.951070: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-02 21:29:07.561937: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.561999: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.562004: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/advanced_mia_example-Patched.py", line 20, in <module>
    from tensorflow_privacy.privacy.privacy_tests import utils
ModuleNotFoundError: No module named 'tensorflow_privacy'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/advanced_mia_example-Patched.py'], returncode=1, stdout=b'', stderr=b'2023-02-02 21:29:06.758613: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2023-02-02 21:29:06.919531: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2023-02-02 21:29:06.951070: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n2023-02-02 21:29:07.561937: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer.so.7\'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.561999: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer_plugin.so.7\'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.562004: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\nTraceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/advanced_mia_example-Patched.py", line 20, in <module>\n    from tensorflow_privacy.privacy.privacy_tests import utils\nModuleNotFoundError: No module named \'tensorflow_privacy\'\n')
<Future at 0x7f3096017580 state=finished returned CompletedProcess>
Standard Error 2023-02-02 21:29:07.434561: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-02 21:29:07.559534: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-02 21:29:07.591664: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-02 21:29:08.088683: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:08.088730: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:08.088736: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/albert_encoder_test-Patched.py", line 14, in <module>
    from official.nlp.modeling.networks import albert_encoder
ModuleNotFoundError: No module named 'official'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/albert_encoder_test-Patched.py'], returncode=1, stdout=b'', stderr=b'2023-02-02 21:29:07.434561: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2023-02-02 21:29:07.559534: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2023-02-02 21:29:07.591664: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n2023-02-02 21:29:08.088683: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer.so.7\'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:08.088730: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer_plugin.so.7\'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:08.088736: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\nTraceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/albert_encoder_test-Patched.py", line 14, in <module>\n    from official.nlp.modeling.networks import albert_encoder\nModuleNotFoundError: No module named \'official\'\n')
<Future at 0x7f309601e6a0 state=finished returned CompletedProcess>
Standard Error 2023-02-02 21:29:08.351884: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-02 21:29:08.492918: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-02 21:29:08.520784: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-02 21:29:09.203346: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:09.203383: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:09.203388: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/albert_encoder-Patched.py", line 13, in <module>
    from official.modeling import activations
ModuleNotFoundError: No module named 'official'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/albert_encoder-Patched.py'], returncode=1, stdout=b'', stderr=b'2023-02-02 21:29:08.351884: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2023-02-02 21:29:08.492918: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2023-02-02 21:29:08.520784: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n2023-02-02 21:29:09.203346: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer.so.7\'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:09.203383: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer_plugin.so.7\'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:09.203388: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\nTraceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/albert_encoder-Patched.py", line 13, in <module>\n    from official.modeling import activations\nModuleNotFoundError: No module named \'official\'\n')
<Future at 0x7f309601ea00 state=finished returned CompletedProcess>
Standard Error 2023-02-02 21:29:06.044954: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-02 21:29:06.219203: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-02 21:29:06.273487: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-02 21:29:07.100901: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.101033: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:07.101055: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host '129.173.67.60'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host '129.173.67.60'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host '129.173.67.60'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/addition-Patched.py", line 23, in <module>
    concrete_function = add.get_concrete_function(x, y)
  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py", line 1239, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py", line 1219, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py", line 785, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 2523, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 2760, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 2670, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 1247, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py", line 677, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 1233, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 1222, in autograph_handler
    return autograph.converted_call(
  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_fileun535ehd.py", line 8, in tf__add
    ag__.converted_call(ag__.ld(custom_method), (ag__.converted_call(ag__.ld(tf).add, (ag__.ld(x), ag__.ld(y)), dict(name='z'), fscope),), dict(imports='import tensorflow as tf', function_to_run='tf.add(*args, **kwargs)', method_object=None, function_args=[ag__.converted_call(ag__.ld(eval), ('x',), None, fscope), ag__.converted_call(ag__.ld(eval), ('y',), None, fscope)], function_kwargs={'name': ag__.converted_call(ag__.ld(eval), ("'z'",), None, fscope)}, max_wait_secs=0), fscope)
  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_filem_r1ddmf.py", line 10, in tf__custom_method
    result = ag__.converted_call(ag__.ld(send_request), (), dict(imports=ag__.ld(imports), function_to_run=ag__.ld(function_to_run), function_args=ag__.ld(function_args), function_kwargs=ag__.ld(function_kwargs), max_wait_secs=ag__.ld(max_wait_secs), method_object=ag__.ld(method_object), custom_class=ag__.ld(custom_class)), fscope)
  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_filebwcsn361.py", line 25, in tf__send_request
    run_data = ag__.converted_call(ag__.ld(pickle).dumps, (ag__.ld(function_details),), None, fscope)
  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 371, in converted_call
    return py_builtins.overload_of(f)(*args)
TypeError: in user code:

    File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/addition-Patched.py", line 17, in add  *
        custom_method(
    File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/addition-Patched.py", line 8, in custom_method  *
        result = send_request(imports=imports, function_to_run=function_to_run, function_args=function_args, function_kwargs=function_kwargs, max_wait_secs=max_wait_secs, method_object=method_object, custom_class=custom_class)
    File "/home/saurabh/code-energy-consumption/server/send_request.py", line 33, in send_request  *
        run_data = pickle.dumps(function_details)

    TypeError: cannot pickle '_thread.RLock' object
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/addition-Patched.py'], returncode=1, stdout=b"sending tf.__version__.split(*args) request to https://129.173.67.60:8080/api/run_experiment\nResult: b'energy_datastart_timeend_time'\nError decoding JSON: Expecting value: line 1 column 1 (char 0)\nsending tf.TensorSpec(*args, **kwargs) request to https://129.173.67.60:8080/api/run_experiment\nResult: b'energy_datastart_timeend_time'\nError decoding JSON: Expecting value: line 1 column 1 (char 0)\nsending tf.TensorSpec(*args, **kwargs) request to https://129.173.67.60:8080/api/run_experiment\nResult: b'energy_datastart_timeend_time'\nError decoding JSON: Expecting value: line 1 column 1 (char 0)\nsending tf.add(*args, **kwargs) request to https://129.173.67.60:8080/api/run_experiment\n", stderr=b'2023-02-02 21:29:06.044954: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2023-02-02 21:29:06.219203: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2023-02-02 21:29:06.273487: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n2023-02-02 21:29:07.100901: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer.so.7\'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.101033: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer_plugin.so.7\'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:07.101055: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host \'129.173.67.60\'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  warnings.warn(\n/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host \'129.173.67.60\'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  warnings.warn(\n/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host \'129.173.67.60\'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  warnings.warn(\nTraceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/addition-Patched.py", line 23, in <module>\n    concrete_function = add.get_concrete_function(x, y)\n  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py", line 1239, in get_concrete_function\n    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)\n  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py", line 1219, in _get_concrete_function_garbage_collected\n    self._initialize(args, kwargs, add_initializers_to=initializers)\n  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py", line 785, in _initialize\n    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 2523, in _get_concrete_function_internal_garbage_collected\n    graph_function, _ = self._maybe_define_function(args, kwargs)\n  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 2760, in _maybe_define_function\n    graph_function = self._create_graph_function(args, kwargs)\n  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 2670, in _create_graph_function\n    func_graph_module.func_graph_from_py_func(\n  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 1247, in func_graph_from_py_func\n    func_outputs = python_func(*func_args, **func_kwargs)\n  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py", line 677, in wrapped_fn\n    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 1233, in autograph_handler\n    raise e.ag_error_metadata.to_exception(e)\n  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 1222, in autograph_handler\n    return autograph.converted_call(\n  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call\n    result = converted_f(*effective_args, **kwargs)\n  File "/tmp/__autograph_generated_fileun535ehd.py", line 8, in tf__add\n    ag__.converted_call(ag__.ld(custom_method), (ag__.converted_call(ag__.ld(tf).add, (ag__.ld(x), ag__.ld(y)), dict(name=\'z\'), fscope),), dict(imports=\'import tensorflow as tf\', function_to_run=\'tf.add(*args, **kwargs)\', method_object=None, function_args=[ag__.converted_call(ag__.ld(eval), (\'x\',), None, fscope), ag__.converted_call(ag__.ld(eval), (\'y\',), None, fscope)], function_kwargs={\'name\': ag__.converted_call(ag__.ld(eval), ("\'z\'",), None, fscope)}, max_wait_secs=0), fscope)\n  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call\n    result = converted_f(*effective_args, **kwargs)\n  File "/tmp/__autograph_generated_filem_r1ddmf.py", line 10, in tf__custom_method\n    result = ag__.converted_call(ag__.ld(send_request), (), dict(imports=ag__.ld(imports), function_to_run=ag__.ld(function_to_run), function_args=ag__.ld(function_args), function_kwargs=ag__.ld(function_kwargs), max_wait_secs=ag__.ld(max_wait_secs), method_object=ag__.ld(method_object), custom_class=ag__.ld(custom_class)), fscope)\n  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call\n    result = converted_f(*effective_args, **kwargs)\n  File "/tmp/__autograph_generated_filebwcsn361.py", line 25, in tf__send_request\n    run_data = ag__.converted_call(ag__.ld(pickle).dumps, (ag__.ld(function_details),), None, fscope)\n  File "/home/saurabh/.local/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 371, in converted_call\n    return py_builtins.overload_of(f)(*args)\nTypeError: in user code:\n\n    File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/addition-Patched.py", line 17, in add  *\n        custom_method(\n    File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/addition-Patched.py", line 8, in custom_method  *\n        result = send_request(imports=imports, function_to_run=function_to_run, function_args=function_args, function_kwargs=function_kwargs, max_wait_secs=max_wait_secs, method_object=method_object, custom_class=custom_class)\n    File "/home/saurabh/code-energy-consumption/server/send_request.py", line 33, in send_request  *\n        run_data = pickle.dumps(function_details)\n\n    TypeError: cannot pickle \'_thread.RLock\' object\n\n')
<Future at 0x7f30970c4fa0 state=finished returned CompletedProcess>
Standard Error 2023-02-02 21:29:08.481175: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-02 21:29:08.658686: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-02 21:29:08.691654: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-02 21:29:09.300202: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:09.300246: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:09.300253: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/adjacency_test-Patched.py", line 13, in <module>
    from tensorflow_gnn.graph import adjacency
ModuleNotFoundError: No module named 'tensorflow_gnn'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/adjacency_test-Patched.py'], returncode=1, stdout=b'', stderr=b'2023-02-02 21:29:08.481175: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2023-02-02 21:29:08.658686: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2023-02-02 21:29:08.691654: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n2023-02-02 21:29:09.300202: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer.so.7\'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:09.300246: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer_plugin.so.7\'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:09.300253: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\nTraceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/adjacency_test-Patched.py", line 13, in <module>\n    from tensorflow_gnn.graph import adjacency\nModuleNotFoundError: No module named \'tensorflow_gnn\'\n')
<Future at 0x7f309601ee80 state=finished returned CompletedProcess>
Standard Error 2023-02-02 21:29:08.624773: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-02 21:29:08.781882: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-02 21:29:08.831106: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-02 21:29:09.297799: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:09.297844: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:09.297851: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/analysis-Patched.py", line 16, in <module>
    import maybe_download
ModuleNotFoundError: No module named 'maybe_download'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/analysis-Patched.py'], returncode=1, stdout=b'', stderr=b'2023-02-02 21:29:08.624773: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2023-02-02 21:29:08.781882: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2023-02-02 21:29:08.831106: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n2023-02-02 21:29:09.297799: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer.so.7\'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:09.297844: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer_plugin.so.7\'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:09.297851: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\nTraceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/analysis-Patched.py", line 16, in <module>\n    import maybe_download\nModuleNotFoundError: No module named \'maybe_download\'\n')
<Future at 0x7f309601efa0 state=finished returned CompletedProcess>
Standard Error 2023-02-02 21:29:08.428547: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-02 21:29:08.565145: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-02 21:29:08.656644: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-02 21:29:09.285610: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:09.285652: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-02 21:29:09.285657: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/and-Patched.py", line 11, in <module>
    from onnx_tf.handlers.backend_handler import BackendHandler
ModuleNotFoundError: No module named 'onnx_tf'
CompletedProcess(args=['python3', './code-dataset/demo-staging-area/and-Patched.py'], returncode=1, stdout=b'', stderr=b'2023-02-02 21:29:08.428547: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2023-02-02 21:29:08.565145: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n2023-02-02 21:29:08.656644: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n2023-02-02 21:29:09.285610: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer.so.7\'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:09.285652: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library \'libnvinfer_plugin.so.7\'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n2023-02-02 21:29:09.285657: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\nTraceback (most recent call last):\n  File "/home/saurabh/code-energy-consumption/client_agent/./code-dataset/demo-staging-area/and-Patched.py", line 11, in <module>\n    from onnx_tf.handlers.backend_handler import BackendHandler\nModuleNotFoundError: No module named \'onnx_tf\'\n')
<Future at 0x7f309601ec40 state=finished returned CompletedProcess>
